module.exports = {
  localeGroups: ['common', 'giveaway'],
  MIRROR: [
    'LOKMAN', 'ANSONLO', 'ALTON',
    'STANLEY', 'KEUNGTO', 'AK',
    'FRANKIE', 'JER', 'IAN',
    'EDAN', 'TIGER', 'JEREMY',
  ],
  CODE: {
    Lokman: 'LOKMANCREW',
    'Anson Lo': 'ANSONLOCREW',
    Alton: 'ALTONCREW',
    AK: 'AKCREW',
    'Keung To': 'KEUNGTOCREW',
    Stanley: 'STANLEYCREW',
    Frankie: 'FRANKIECREW',
    Jer: 'JERCREW',
    Ian: 'IANCREW',
    Edan: 'EDANCREW',
    Tiger: 'TIGERCREW',
    Jeremy: 'JEREMYCREW',
  },
  runnerDuration: 40,
  poptinUserId: 'ae733fe465023',
  poptinDataId_zhHK: '187b66784c9dc',
  poptinDataId_en: '43c8ba1a61ca1',
  videoId: 'xo6PBuevB84',
  couponCode: 'MIRROR-15OFF',
  kicksCrewUrl: 'https://www.kickscrew.com',
  instagramUrl: 'https://www.instagram.com/kickscrewcom',
  facebookUrl: 'https://www.facebook.com/kcrewcom',
  linkedinUrl: 'https://www.linkedin.com/company/kickscrew/mycompany/',
  kicksCrewAppUrl: 'https://kickscrew.onelink.me/ikAv/qjbfdm7x?af_qr=true',
};