module.exports = {
  localeGroups: ['common', 'giveaway'],
  MIRROR: [
    'LOKMAN', 'ANSONLO', 'ALTON',
    'STANLEY', 'KEUNGTO', 'AK',
    'FRANKIE', 'JER', 'IAN',
    'EDAN', 'TIGER', 'JEREMY',
  ],
  runnerDuration: 40,
  poptinUserId: 'ae733fe465023',
  poptinDataId_zhHK: 'ddf1d6f702a4e',
  poptinDataId_en: '43c8ba1a61ca1',
  videoId: '9LFs-FrJokU',
  couponCode: 'MIRROR10OFF',
  kicksCrewUrl: 'https://www.kickscrew.com',
  instagramUrl: 'https://www.instagram.com/kickscrewcom',
  facebookUrl: 'https://www.facebook.com/kcrewcom',
  linkedinUrl: 'https://www.linkedin.com/company/kickscrew/mycompany/',
  kicksCrewAppUrl: 'https://kickscrew.onelink.me/ikAv/qjbfdm7x?af_qr=true',
};
